# Generated by Django 3.2.7 on 2021-09-04 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.CharField(max_length=8)),
                ('edad', models.FloatField()),
                ('talla', models.FloatField()),
                ('peso', models.FloatField()),
                ('genero', models.CharField(choices=[('MA', 'Masculino'), ('FE', 'Femenino')], max_length=2)),
                ('nivelactividad', models.FloatField(choices=[(1, 'No Muy Activo'), (2, 'Medianamente Activo'), (3, 'Activo'), (4, 'Muy Activo')], null=True)),
                ('alimentacion', models.FloatField(choices=[(2, 'Opción Vegana'), (1, 'Opción Vegetariana'), (3, 'Opción con Carne')], null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('receta', models.TextField()),
                ('calorias', models.FloatField(null=True)),
                ('alimentacion', models.FloatField(choices=[(2, 'Opción Vegana'), (1, 'Opción Vegetariana'), (3, 'Opción con Carne')], null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.categoria')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.proveedor')),
            ],
        ),
    ]
