# Generated by Django 3.2.7 on 2021-09-11 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='objetivo',
            field=models.FloatField(choices=[(1, 'Bajar de peso'), (2, 'Mantener tu peso'), (3, 'Subir de peso')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nivelactividad',
            field=models.FloatField(choices=[(1.2, 'No Muy Activo'), (1.375, 'Medianamente Activo'), (1.55, 'Activo'), (1.72, 'Muy Activo')], null=True),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimentacion', models.FloatField(choices=[(2, 'Opción Vegana'), (1, 'Opción Vegetariana'), (3, 'Opción con Carne')], null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.menu')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plato')),
            ],
        ),
    ]
