# Generated by Django 3.2.7 on 2021-09-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_menu_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='fecha_creacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='alimentacion',
            field=models.IntegerField(choices=[(2, 'Opción Vegana'), (1, 'Opción Vegetariana'), (3, 'Opción con Carne')], null=True),
        ),
    ]
