# Generated by Django 3.2.7 on 2021-09-18 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210917_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='platos')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.plato')),
            ],
        ),
    ]
