# Generated by Django 3.2.7 on 2021-09-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_platoimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='ingredientes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
