# Generated by Django 3.2.7 on 2021-10-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_plato_ingredientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='carbos',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='plato',
            name='grasas',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='plato',
            name='proteinas',
            field=models.FloatField(null=True),
        ),
    ]
