# Generated by Django 3.2.7 on 2021-10-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211009_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='objetivo',
            field=models.FloatField(choices=[(-500, 'Bajar de peso'), (0, 'Mantener tu peso'), (500, 'Subir de peso')], null=True),
        ),
    ]
