# Generated by Django 3.2.7 on 2021-10-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_profile_objetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='platos'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='alimentacion',
            field=models.IntegerField(choices=[(2, 'Vegana'), (1, 'Vegetariana'), (3, 'Carne')], null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='alimentacion',
            field=models.FloatField(choices=[(2, 'Vegana'), (1, 'Vegetariana'), (3, 'Carne')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='alimentacion',
            field=models.FloatField(choices=[(2, 'Vegana'), (1, 'Vegetariana'), (3, 'Carne')], null=True),
        ),
        migrations.DeleteModel(
            name='PlatoImage',
        ),
    ]
