# Generated by Django 3.2.7 on 2021-10-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211009_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='lista',
            field=models.JSONField(null=True),
        ),
    ]
